import React, { useState, useMemo } from 'react';
import { ALL_DISTRICTS } from '@/data/districts';
import { INDICATORS } from '@/config/indicators';
import { getIndicatorValuesForDistrict } from '@/data/demoData';
import { DEFAULT_YEAR } from '@/config/years';
import confetti from 'canvas-confetti';
import {
  Brain,
  Sparkles,
  TrendingUp,
  ShieldCheck,
  AlertTriangle,
  Sliders,
  FileText,
  Copy,
  Check,
  Target,
  ArrowRight,
  Zap,
  DollarSign,
} from 'lucide-react';

interface PolicyAiCopilotProps {
  initialDistrictId?: string;
}

export default function PolicyAiCopilot({ initialDistrictId = 'lucknow' }: PolicyAiCopilotProps) {
  const [districtId, setDistrictId] = useState(initialDistrictId);
  const [selectedObjective, setSelectedObjective] = useState<'health' | 'education' | 'economy' | 'infrastructure'>('health');
  const [copied, setCopied] = useState(false);

  // Budget Simulation Sliders (in Crores ₹)
  const [budgetHealth, setBudgetHealth] = useState(150);
  const [budgetEducation, setBudgetEducation] = useState(120);
  const [budgetInfra, setBudgetInfra] = useState(200);
  const [budgetWater, setBudgetWater] = useState(80);

  const district = useMemo(
    () => ALL_DISTRICTS.find((d) => d.id === districtId) || ALL_DISTRICTS[0],
    [districtId]
  );

  // Derive metrics for this district
  const healthData = useMemo(() => getIndicatorValuesForDistrict(district.id, 'healthcare', DEFAULT_YEAR), [district.id]);
  const eduData = useMemo(() => getIndicatorValuesForDistrict(district.id, 'education', DEFAULT_YEAR), [district.id]);
  const waterData = useMemo(() => getIndicatorValuesForDistrict(district.id, 'water', DEFAULT_YEAR), [district.id]);
  const infraData = useMemo(() => getIndicatorValuesForDistrict(district.id, 'roads', DEFAULT_YEAR), [district.id]);

  const literacyVal = eduData.find((m) => m.metric === 'literacy_rate')?.value ?? 70;
  const imrVal = healthData.find((m) => m.metric === 'infant_mortality_rate')?.value ?? 42;
  const waterVal = waterData.find((m) => m.metric === 'piped_water_coverage')?.value ?? 55;
  const roadsVal = infraData.find((m) => m.metric === 'villages_connected')?.value ?? 80;

  // Projected outcomes based on simulation
  const projectedIMR = Math.max(12, Math.round((imrVal - (budgetHealth / 150) * 8.5) * 10) / 10);
  const projectedLiteracy = Math.min(99.5, Math.round((literacyVal + (budgetEducation / 120) * 5.2) * 10) / 10);
  const projectedWater = Math.min(100, Math.round((waterVal + (budgetWater / 80) * 14) * 10) / 10);
  const projectedRoads = Math.min(100, Math.round((roadsVal + (budgetInfra / 200) * 8) * 10) / 10);

  const totalBudget = budgetHealth + budgetEducation + budgetInfra + budgetWater;

  const handleSimulate = () => {
    confetti({
      particleCount: 80,
      spread: 70,
      origin: { y: 0.6 },
      colors: ['#D4AF37', '#10B981', '#6366F1'],
    });
  };

  const policyDossierText = `
GOVERNMENT OF INDIA & STATE CIVIC INTELLIGENCE DOSSIER
=====================================================
Target District: ${district.name} (${district.stateId.toUpperCase()})
Date: ${new Date().toLocaleDateString('en-IN', { year: 'numeric', month: 'long', day: 'numeric' })}
Objective Focus: ${selectedObjective.toUpperCase()} INTERVENTION PROGRAM

BASELINE DIAGNOSTICS:
- Infant Mortality Rate: ${imrVal} per 1,000 live births
- Literacy Rate: ${literacyVal}%
- Piped Drinking Water Access: ${waterVal}%
- All-Weather Road Connectivity: ${roadsVal}%

RECOMMENDED STRATEGIC 5-YEAR INTERVENTIONS:
1. Healthcare: Infuse ₹${budgetHealth} Cr for maternal-child clinics, primary health center electrification, and ambulance telemetry.
   → Projected IMR reduction: ${imrVal} → ${projectedIMR}
2. Education: Allocate ₹${budgetEducation} Cr for STEM laboratories, digital smart-boards, and secondary female retention programs.
   → Projected Literacy Gain: ${literacyVal}% → ${projectedLiteracy}%
3. Drinking Water: Deploy ₹${budgetWater} Cr toward Har Ghar Jal pipeline automation & groundwater recharge reservoirs.
   → Projected Piped Coverage: ${waterVal}% → ${projectedWater}%
4. Road Infrastructure: Invest ₹${budgetInfra} Cr for PMGSY last-mile tarmac connectivity to agrarian clusters.
   → Projected Connectivity: ${roadsVal}% → ${projectedRoads}%

TOTAL ALLOCATED ENVELOPE: ₹${totalBudget} Crores
ESTIMATED POPULATION BENEFICIARIES: 840,000+ residents
=====================================================
Generated by India Data Atlas AI Policy Copilot
  `.trim();

  const handleCopy = () => {
    navigator.clipboard.writeText(policyDossierText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  return (
    <div className="space-y-6">
      {/* Top Banner */}
      <div className="rounded-2xl border border-gold-500/30 bg-gradient-to-r from-base-950 via-base-900 to-base-950 p-6 shadow-luxury">
        <div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between">
          <div className="flex items-start gap-3.5">
            <div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-xl border border-gold-500/40 bg-gold-500/10 text-gold-400 shadow-gold">
              <Brain size={24} />
            </div>
            <div>
              <div className="inline-flex items-center gap-1.5 rounded-full border border-gold-500/30 bg-gold-500/10 px-2.5 py-0.5 text-[11px] font-mono text-gold-300">
                <Sparkles size={11} />
                AI CIVIC & POLICY SIMULATOR
              </div>
              <h2 className="mt-1 font-display text-xl font-bold text-base-100">
                District Development Strategist & Policy Copilot
              </h2>
              <p className="mt-0.5 text-xs text-base-400">
                Automated multi-year diagnostic analysis, bottleneck detection, and quantified budget impact modeling for Indian district magistrates & policy makers.
              </p>
            </div>
          </div>

          {/* District Selector */}
          <div className="flex items-center gap-2">
            <span className="text-xs text-base-400 font-mono">District:</span>
            <select
              value={districtId}
              onChange={(e) => setDistrictId(e.target.value)}
              className="rounded-xl border border-gold-500/30 bg-base-950 px-3.5 py-2 text-sm font-semibold text-gold-300 focus:border-gold-500 focus:outline-none shadow-panel"
            >
              {ALL_DISTRICTS.map((d) => (
                <option key={d.id} value={d.id}>
                  {d.name} ({d.stateId.replace('-', ' ')})
                </option>
              ))}
            </select>
          </div>
        </div>
      </div>

      {/* Grid: Diagnostics & AI Recommendations */}
      <div className="grid gap-6 lg:grid-cols-2">
        {/* Left: AI Diagnosis & Priority Interventions */}
        <div className="rounded-2xl glass-panel p-6 shadow-luxury flex flex-col justify-between">
          <div>
            <div className="flex items-center justify-between border-b border-base-800 pb-3">
              <h3 className="font-display text-base font-semibold text-base-100 flex items-center gap-2">
                <ShieldCheck size={18} className="text-signal-emerald" />
                Root-Cause Bottleneck Diagnosis
              </h3>
              <span className="rounded bg-gold-500/10 px-2 py-0.5 text-[10px] font-mono text-gold-300 border border-gold-500/20">
                {district.name} Profile
              </span>
            </div>

            <div className="mt-4 space-y-3">
              <div className="rounded-xl border border-base-800 bg-base-950/60 p-3.5">
                <div className="flex items-center justify-between">
                  <span className="text-xs font-semibold text-base-200">1. Maternal & Infant Healthcare Gap</span>
                  <span className={`text-xs font-bold tabular-nums ${imrVal > 40 ? 'text-signal-rose' : 'text-signal-emerald'}`}>
                    IMR: {imrVal} / 1k
                  </span>
                </div>
                <p className="mt-1 text-xs text-base-400 leading-relaxed">
                  {imrVal > 40
                    ? `Infant mortality in ${district.name} is above state benchmark. Primary bottleneck is institutional delivery accessibility in rural sub-divisions.`
                    : `Healthcare infrastructure is relatively resilient, but doctor-to-population density in rural PHCs requires capacity reinforcement.`}
                </p>
              </div>

              <div className="rounded-xl border border-base-800 bg-base-950/60 p-3.5">
                <div className="flex items-center justify-between">
                  <span className="text-xs font-semibold text-base-200">2. Literacy & Workforce Readiness</span>
                  <span className="text-xs font-bold text-gold-300 tabular-nums">
                    Literacy: {literacyVal}%
                  </span>
                </div>
                <p className="mt-1 text-xs text-base-400 leading-relaxed">
                  Gross enrollment is solid, but secondary school female retention drops after age 14. Priority is digital lab integration and vocational skilling centers.
                </p>
              </div>

              <div className="rounded-xl border border-base-800 bg-base-950/60 p-3.5">
                <div className="flex items-center justify-between">
                  <span className="text-xs font-semibold text-base-200">3. Drinking Water & Critical Infrastructure</span>
                  <span className="text-xs font-bold text-signal-teal tabular-nums">
                    Piped: {waterVal}% · Roads: {roadsVal}%
                  </span>
                </div>
                <p className="mt-1 text-xs text-base-400 leading-relaxed">
                  Last-mile piped connections need acceleration in 18 peripheral blocks to attain 100% saturation under Jal Jeevan Mission targets.
                </p>
              </div>
            </div>
          </div>

          {/* Strategic Objective Selector */}
          <div className="mt-6 border-t border-base-800 pt-4">
            <span className="text-xs font-mono uppercase tracking-wider text-base-400">Select Primary Strategic Target:</span>
            <div className="mt-2 grid grid-cols-2 sm:grid-cols-4 gap-2">
              {[
                { id: 'health', label: 'Health First', icon: Zap },
                { id: 'education', label: 'Education', icon: Target },
                { id: 'infrastructure', label: 'Infra & Roads', icon: TrendingUp },
                { id: 'economy', label: 'Water Security', icon: Sparkles },
              ].map((obj) => (
                <button
                  key={obj.id}
                  onClick={() => setSelectedObjective(obj.id as any)}
                  className={`flex items-center justify-center gap-1.5 rounded-xl border px-3 py-2 text-xs font-medium transition-all ${
                    selectedObjective === obj.id
                      ? 'border-gold-500 bg-gold-500/15 text-gold-300 shadow-gold'
                      : 'border-base-700 bg-base-900/60 text-base-400 hover:text-base-200'
                  }`}
                >
                  <obj.icon size={13} />
                  {obj.label}
                </button>
              ))}
            </div>
          </div>
        </div>

        {/* Right: What-If Budget Simulator & Outcomes */}
        <div className="rounded-2xl glass-panel p-6 shadow-luxury flex flex-col justify-between">
          <div>
            <div className="flex items-center justify-between border-b border-base-800 pb-3">
              <h3 className="font-display text-base font-semibold text-base-100 flex items-center gap-2">
                <Sliders size={18} className="text-gold-400" />
                "What-If" Budget Allocation Simulation
              </h3>
              <span className="font-mono text-xs font-bold text-gold-300">
                Total: ₹{totalBudget} Cr
              </span>
            </div>

            {/* Sliders */}
            <div className="mt-4 space-y-4">
              <div>
                <div className="flex justify-between text-xs mb-1">
                  <span className="text-base-300 font-medium">Healthcare & Hospital Beds</span>
                  <span className="font-mono font-semibold text-gold-300">₹{budgetHealth} Cr</span>
                </div>
                <input
                  type="range"
                  min="20"
                  max="300"
                  step="10"
                  value={budgetHealth}
                  onChange={(e) => setBudgetHealth(Number(e.target.value))}
                  className="w-full accent-[#D4AF37] cursor-pointer"
                />
              </div>

              <div>
                <div className="flex justify-between text-xs mb-1">
                  <span className="text-base-300 font-medium">Education & Schools Modernization</span>
                  <span className="font-mono font-semibold text-gold-300">₹{budgetEducation} Cr</span>
                </div>
                <input
                  type="range"
                  min="20"
                  max="300"
                  step="10"
                  value={budgetEducation}
                  onChange={(e) => setBudgetEducation(Number(e.target.value))}
                  className="w-full accent-[#D4AF37] cursor-pointer"
                />
              </div>

              <div>
                <div className="flex justify-between text-xs mb-1">
                  <span className="text-base-300 font-medium">All-Weather Rural Roads (PMGSY)</span>
                  <span className="font-mono font-semibold text-gold-300">₹{budgetInfra} Cr</span>
                </div>
                <input
                  type="range"
                  min="30"
                  max="400"
                  step="10"
                  value={budgetInfra}
                  onChange={(e) => setBudgetInfra(Number(e.target.value))}
                  className="w-full accent-[#D4AF37] cursor-pointer"
                />
              </div>

              <div>
                <div className="flex justify-between text-xs mb-1">
                  <span className="text-base-300 font-medium">Har Ghar Jal Piped Water Network</span>
                  <span className="font-mono font-semibold text-gold-300">₹{budgetWater} Cr</span>
                </div>
                <input
                  type="range"
                  min="10"
                  max="200"
                  step="10"
                  value={budgetWater}
                  onChange={(e) => setBudgetWater(Number(e.target.value))}
                  className="w-full accent-[#D4AF37] cursor-pointer"
                />
              </div>
            </div>

            {/* Projected Impact Cards */}
            <div className="mt-5 grid grid-cols-2 sm:grid-cols-4 gap-2.5">
              <div className="rounded-xl border border-signal-emerald/30 bg-signal-emerald/5 p-3 text-center">
                <span className="text-[10px] text-base-400 font-mono">Projected IMR</span>
                <p className="mt-1 text-base font-bold text-signal-emerald tabular-nums">
                  {projectedIMR} <span className="text-[10px]">(-{(imrVal - projectedIMR).toFixed(1)})</span>
                </p>
              </div>

              <div className="rounded-xl border border-gold-500/30 bg-gold-500/5 p-3 text-center">
                <span className="text-[10px] text-base-400 font-mono">Literacy Rate</span>
                <p className="mt-1 text-base font-bold text-gold-300 tabular-nums">
                  {projectedLiteracy}% <span className="text-[10px]">(+{(projectedLiteracy - literacyVal).toFixed(1)}%)</span>
                </p>
              </div>

              <div className="rounded-xl border border-signal-indigo/30 bg-signal-indigo/5 p-3 text-center">
                <span className="text-[10px] text-base-400 font-mono">Piped Water</span>
                <p className="mt-1 text-base font-bold text-signal-indigo tabular-nums">
                  {projectedWater}% <span className="text-[10px]">(+{(projectedWater - waterVal).toFixed(1)}%)</span>
                </p>
              </div>

              <div className="rounded-xl border border-signal-teal/30 bg-signal-teal/5 p-3 text-center">
                <span className="text-[10px] text-base-400 font-mono">Road Access</span>
                <p className="mt-1 text-base font-bold text-signal-teal tabular-nums">
                  {projectedRoads}% <span className="text-[10px]">(+{(projectedRoads - roadsVal).toFixed(1)}%)</span>
                </p>
              </div>
            </div>
          </div>

          {/* Action buttons */}
          <div className="mt-6 flex flex-wrap items-center gap-3">
            <button
              onClick={handleSimulate}
              className="flex-1 inline-flex items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-gold-500 to-gold-400 px-4 py-2.5 text-xs font-bold text-base-950 shadow-gold hover:opacity-95 transition-all"
            >
              <Sparkles size={14} />
              Run 5-Year Impact Simulation
            </button>
            <button
              onClick={handleCopy}
              className="inline-flex items-center gap-1.5 rounded-xl border border-gold-500/30 bg-base-950 px-3.5 py-2.5 text-xs font-semibold text-gold-300 hover:border-gold-500"
            >
              {copied ? <Check size={14} className="text-signal-emerald" /> : <Copy size={14} />}
              {copied ? 'Dossier Copied' : 'Export Brief'}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
